src/Entity/Spot.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\SpotRepository")
 */
class Spot
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var Role
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Role")
     * @ORM\JoinColumn(nullable=false)
     */
    private $role;

    /**
     * @var Event
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\Event", inversedBy="spots")
     * @ORM\JoinColumn(nullable=false)
     */
    private $event;

    /**
     * @var User
     *
     * @ORM\ManyToOne(targetEntity="App\Entity\User")
     */
    private $user;

//    /**
//     * @ORM\Column(type="string", length=255)
//     */
//    private $status;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isAvailable(): bool
    {
        return $this->user === null;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getRole(): ?Role
    {
        return $this->role;
    }

    public function setRole(?Role $role): self
    {
        $this->role = $role;

        return $this;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(?Event $event): self
    {
        $this->event = $event;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function attemptToReserve(User $user): bool
    {
        if ($this->event->hasUser($user)) {
            return false;
        }

        $this->setUser($user);

        return true;
    }

    public function __toString(): string
    {
        return $this->role->getName();
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Event;
use App\Entity\Spot;
use App\Repository\CategoryRepository;
use App\Repository\EventRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Response;

class HomeController extends AbstractController
{
    /**
     * @var CategoryRepository
     */
    private $categoryRepository;

    /**
     * @var EventRepository
     */
    private $eventRepository;

    public function __construct(
        CategoryRepository $categoryRepository,
        EventRepository $eventRepository
    )
    {
        $this->categoryRepository = $categoryRepository;
        $this->eventRepository = $eventRepository;
    }

    public function indexAction($category = null): Response
    {
        return $this->render('home/dashboard.html.twig', [
            'categories' => $this->categoryRepository->findAllMainCategoriesWithCounts(),
            'events' => $this->eventRepository->findAllEventsByCategory($category)
        ]);
    }


    public function eventAction(Event $event): Response
    {
        return $this->render('home/event.html.twig', [
            'event' => $event
        ]);
    }

    public function joinEventAction(Spot $spot): RedirectResponse
    {
        if (!$spot->isAvailable()) {
            $this->addFlash('warning', 'Sorry, but this spot is already occupied :c');

            return $this->redirectToRoute('app_event', ['id' => $spot->getEvent()->getId()]);
        }

        if (!$spot->attemptToReserve($this->getUser())) {
            $this->addFlash('warning', 'Sorry! You\'re already in our team');

            return $this->redirectToRoute('app_event', ['id' => $spot->getEvent()->getId()]);
        }

        $this->eventRepository->save($spot);

        $this->addFlash('success', 'Yaaay! You have teamed up!');

        return $this->redirectToRoute('app_event', ['id' => $spot->getEvent()->getId()]);
    }
}

templates/home/dashboard.html.twig
{% extends 'base.html.twig' %}

{% block title %}Your Dashboard{% endblock %}

{% block container %}
    {% if app.user %}
        <h1>Hello {{ app.user.name }}!</h1>
        {% if app.user.isConfirmed == false %}
            Confirm your account to use all features.
        {% endif %}
    {% else %}
        <h1> Hello guest!</h1>
        <div class="alert alert-warning" role="alert">
            Sign in to access all of the features...
        </div>
    {% endif %}
    <div class="row">
        <div class="col-12">
            <div class="row">
                <div class="col-8">
                    {% for event in events %}
                        <div class="card mb-4">
                            <svg class="bd-placeholder-img card-img-top" width="100%" height="180"
                                 xmlns="http://www.w3.org/2000/svg" preserveAspectRatio="xMidYMid slice"
                                 focusable="false"
                                 role="img" aria-label="Placeholder: Image cap">
                                <rect fill="#868e96" width="100%" height="100%"></rect>
                                <text fill="#dee2e6" dy=".3em" x="50%" y="50%">Image cap</text>
                            </svg>
                            <div class="card-body">
                                <h5 class="card-title"><a href="{{ path('app_event', {id: event.id}) }}">{{ event.title }}</a></h5>
                                <p class="card-text">{{ event.description }}</p>
                            </div>
                            <div class="card-body">
                                <div class="float-left" style="font-size: 13px;">
                                    {{ event.dateFrom|date("m/d/Y") }} - {{ event.dateTo|date("m/d/Y") }}<br>
                                    {{ event.location }}
                                </div>
                                {% for spot in event.spots %}
                                    <span class="{% if spot.isAvailable %}badge-success {% else %} badge-dark {% endif %}
                            float-right badge m-1">{{ spot.role.name }}</span>
                                {% endfor %}
                            </div>
                        </div>
                    {% endfor %}
                </div>
                <div class="col-4">
                    <div class="card" style="width: 18rem;">
                        <div class="card-body">
                            <h5 class="card-title">Event Categories</h5>
                        </div>
                        <ul class="list-group list-group-flush">
                            {% for category in categories %}
                                <a href="#"
                                   class="list-group-item list-group-item-action  d-flex justify-content-between align-items-center">
                                    {{ category.name }}
                                    <span class="badge badge-primary badge-pill">14</span>
                                </a>
                            {% endfor %}
                        </ul>
                    </div>
                    tags,
                    categories,
                    search
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/home/event.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {{ event.title }}
{% endblock %}

{% block beforeContainer %}
    <div class="jumbotron jumbotron-fluid event-jumbotron">
        <div class="container">
            <h1 class="display-4">{{ event.title }}</h1>
            <p class="lead">{{ event.dateFrom|date("m/d/Y") }} - {{ event.dateTo|date("m/d/Y") }}
                | {{ event.location }} by <a class='btn-link' href="#">@{{ event.owner.name }}</a>
            </p>
        </div>
    </div>
    <div class="container">
        <div class="row">

            <div class="col-12 col-lg-7 mb-4">
                {{ event.description }}
            </div>
            <div class="col-12 col-lg-5">
                <table class="table table-sm table-bordered table-striped">
                    <thead>
                    <tr>
                        <th>Role</th>
                        <th class="text-center">Availability</th>
                        <th class="text-center">Action</th>
                    </tr>
                    </thead>
                    <tbody>
                    {% for spot in event.spots %}
                        <tr>
                            <td>{{ spot.role.name }}</td>
                            <td class="text-center">
                                {% if spot.isAvailable %}
                                    <h5><span class="mt-1 badge badge-pill badge-success">Available</span></h5>
                                {% else %}
                                    <h5><span class="badge badge-pill badge-dark">Occupied</span></h5>
                                {% endif %}
                            </td>
                            <td>
                                {% if app.user and spot.available and not event.hasUser(app.user) %}
                                    <a href="{{ path('app_event_join', {'id': spot.id }) }}"
                                       class="btn btn-sm btn-block btn-primary">Join the team
                                    </a>
                                {% elseif app.user %}

                                {% else %}
                                    <button type="button" class="btn btn-sm btn-block btn-secondary disabled">You need
                                        to
                                        login to join the team
                                    </button>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
{% endblock %}